
// Generated by Cadence Genus(TM) Synthesis Solution 18.14-s037_1
// Generated on: Dec  5 2024 07:13:50 CST (Dec  5 2024 13:13:50 UTC)

// Verification Directory fv/mac 

module mac(IN, W, clk, rstb, OUT);
  input [3:0] IN, W;
  input clk, rstb;
  output [11:0] OUT;
  wire [3:0] IN, W;
  wire clk, rstb;
  wire [11:0] OUT;
  wire [10:0] B;
  wire [6:0] A;
  wire [3:0] counter;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, UNCONNECTED2,
       UNCONNECTED3, UNCONNECTED4, UNCONNECTED5, UNCONNECTED6;
  wire UNCONNECTED7, UNCONNECTED8, UNCONNECTED9, UNCONNECTED10,
       UNCONNECTED11, UNCONNECTED12, UNCONNECTED13, UNCONNECTED14;
  wire UNCONNECTED15, UNCONNECTED16, UNCONNECTED17, UNCONNECTED18,
       UNCONNECTED19, UNCONNECTED20, UNCONNECTED21, UNCONNECTED22;
  wire UNCONNECTED23, UNCONNECTED24, UNCONNECTED25, UNCONNECTED26,
       UNCONNECTED27, UNCONNECTED28, UNCONNECTED29, UNCONNECTED30;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_29, n_30, n_31;
  wire n_32, n_33, n_34, n_35, n_36, n_37, n_38, n_39;
  wire n_40, n_41, n_42, n_43, n_44, n_45, n_46, n_47;
  wire n_48, n_49, n_50, n_51, n_52, n_53, n_54, n_55;
  wire n_56, n_57, n_58, n_59, n_60, n_61, n_62, n_63;
  wire n_64, n_65, n_66, n_67, n_68, n_69, n_70, n_71;
  wire n_72, n_73, n_74, n_75, n_76, n_77, n_78, n_79;
  wire n_80, n_81, n_82, n_83, n_84, n_85, n_86, n_87;
  wire n_88, n_89, n_90, n_91, n_92, n_93, n_94, n_95;
  wire n_96, n_97, n_98, n_99, n_100, n_101, n_102, n_103;
  wire n_104, n_105, n_106, n_107, n_108, n_109, n_110, n_111;
  wire n_112, n_113, n_114, n_115, n_116, n_117, n_118, n_119;
  wire n_120, n_121, n_122, n_123, n_124, n_125, n_126, n_127;
  wire n_128, n_129, n_130, n_131, n_132, n_133, n_134, n_135;
  wire n_136;
  assign OUT[10] = OUT[11];
  DFFR_X1 \B_reg[10] (.RN (rstb), .CK (clk), .D (n_136), .Q (B[10]),
       .QN (UNCONNECTED));
  DFFR_X1 \B_reg[9] (.RN (rstb), .CK (clk), .D (n_135), .Q (B[9]), .QN
       (UNCONNECTED0));
  NOR2_X1 g5800__8780(.A1 (n_133), .A2 (n_134), .ZN (n_136));
  NOR2_X1 g5803__4296(.A1 (n_132), .A2 (n_134), .ZN (n_135));
  XOR2_X1 g5802__3772(.A (n_130), .B (n_109), .Z (n_133));
  DFFR_X1 \B_reg[8] (.RN (rstb), .CK (clk), .D (n_131), .Q (B[8]), .QN
       (UNCONNECTED1));
  XOR2_X1 g5805__1474(.A (n_110), .B (n_129), .Z (n_132));
  DFFR_X1 \B_reg[7] (.RN (rstb), .CK (clk), .D (n_126), .Q (B[7]), .QN
       (UNCONNECTED2));
  NOR2_X1 g5807__4547(.A1 (n_125), .A2 (n_134), .ZN (n_131));
  OAI211_X1 g5806__9682(.A (n_127), .B (n_98), .C1 (n_128), .C2
       (n_100), .ZN (n_130));
  NAND2_X1 g5810__2683(.A1 (n_128), .A2 (n_127), .ZN (n_129));
  NOR2_X1 g5812__1309(.A1 (n_124), .A2 (n_134), .ZN (n_126));
  XOR2_X1 g5809__6877(.A (n_123), .B (n_104), .Z (n_125));
  XOR2_X1 g5814__2900(.A (n_107), .B (n_121), .Z (n_124));
  NAND2_X1 g5811__2391(.A1 (n_123), .A2 (n_103), .ZN (n_128));
  DFFR_X1 \B_reg[6] (.RN (rstb), .CK (clk), .D (n_122), .Q (B[6]), .QN
       (UNCONNECTED3));
  OAI211_X1 g5815__7675(.A (n_119), .B (n_101), .C1 (n_120), .C2
       (n_102), .ZN (n_123));
  NOR2_X1 g5816__7118(.A1 (n_118), .A2 (n_134), .ZN (n_122));
  DFFR_X1 \B_reg[5] (.RN (rstb), .CK (clk), .D (n_116), .Q (B[5]), .QN
       (UNCONNECTED4));
  NAND2_X1 g5819__8757(.A1 (n_120), .A2 (n_119), .ZN (n_121));
  XOR2_X1 g5818__1786(.A (n_117), .B (n_106), .Z (n_118));
  NAND2_X1 g5820__5953(.A1 (n_117), .A2 (n_105), .ZN (n_120));
  AND2_X1 g5821__5703(.A1 (n_115), .A2 (n_113), .ZN (n_116));
  FA_X1 g5822__7114(.A (A[5]), .B (B[5]), .CI (n_111), .CO (n_117), .S
       (n_115));
  DFFR_X1 \B_reg[4] (.RN (rstb), .CK (clk), .D (n_114), .Q (B[4]), .QN
       (UNCONNECTED5));
  AND2_X1 g5824__5266(.A1 (n_112), .A2 (n_113), .ZN (n_114));
  FA_X1 g5830__2250(.A (A[4]), .B (B[4]), .CI (n_96), .CO (n_111), .S
       (n_112));
  XOR2_X1 g5828__6083(.A (n_108), .B (B[9]), .Z (n_110));
  XOR2_X1 g5829__2703(.A (n_108), .B (B[10]), .Z (n_109));
  DFFR_X1 \B_reg[3] (.RN (rstb), .CK (clk), .D (n_99), .Q (B[3]), .QN
       (UNCONNECTED6));
  XOR2_X1 g5825__5795(.A (n_108), .B (B[7]), .Z (n_107));
  NAND2_X1 g5826__7344(.A1 (n_119), .A2 (n_105), .ZN (n_106));
  NAND2_X1 g5827__1840(.A1 (n_127), .A2 (n_103), .ZN (n_104));
  NOR2_X1 g5832__5019(.A1 (A[6]), .A2 (B[7]), .ZN (n_102));
  NAND2_X1 g5831__1857(.A1 (A[6]), .A2 (B[7]), .ZN (n_101));
  OR2_X1 g5833__9906(.A1 (A[6]), .A2 (B[6]), .ZN (n_105));
  NAND2_X1 g5834__8780(.A1 (A[6]), .A2 (B[6]), .ZN (n_119));
  NOR2_X1 g5837__4296(.A1 (A[6]), .A2 (B[9]), .ZN (n_100));
  AND2_X1 g5842__3772(.A1 (n_97), .A2 (n_113), .ZN (n_99));
  NAND2_X1 g5835__1474(.A1 (A[6]), .A2 (B[9]), .ZN (n_98));
  OR2_X1 g5836__4547(.A1 (A[6]), .A2 (B[8]), .ZN (n_103));
  NAND2_X1 g5838__9682(.A1 (A[6]), .A2 (B[8]), .ZN (n_127));
  FA_X1 g5844__2683(.A (A[3]), .B (B[3]), .CI (n_89), .CO (n_96), .S
       (n_97));
  DFFR_X1 \A_reg[6] (.RN (rstb), .CK (clk), .D (n_95), .Q (A[6]), .QN
       (n_108));
  DFFR_X1 \B_reg[2] (.RN (rstb), .CK (clk), .D (n_93), .Q (B[2]), .QN
       (UNCONNECTED7));
  NOR2_X1 g5843__1309(.A1 (n_94), .A2 (n_91), .ZN (n_95));
  DFFR_X1 \A_reg[5] (.RN (rstb), .CK (clk), .D (n_92), .Q (A[5]), .QN
       (UNCONNECTED8));
  XOR2_X1 g5846__6877(.A (n_87), .B (n_75), .Z (n_94));
  AND2_X1 g5849__2900(.A1 (n_90), .A2 (n_113), .ZN (n_93));
  NOR2_X1 g5848__2391(.A1 (n_88), .A2 (n_91), .ZN (n_92));
  FA_X1 g5853__7675(.A (A[2]), .B (B[2]), .CI (n_81), .CO (n_89), .S
       (n_90));
  DFFR_X1 \A_reg[4] (.RN (rstb), .CK (clk), .D (n_85), .Q (A[4]), .QN
       (UNCONNECTED9));
  XOR2_X1 g5851__7118(.A (n_86), .B (n_72), .Z (n_88));
  OAI21_X1 g5852__8757(.A (n_70), .B1 (n_86), .B2 (n_71), .ZN (n_87));
  DFFR_X1 \B_reg[1] (.RN (rstb), .CK (clk), .D (n_83), .Q (B[1]), .QN
       (UNCONNECTED10));
  AND2_X1 g5854__1786(.A1 (n_79), .A2 (n_84), .ZN (n_85));
  FA_X1 g5855__5953(.A (n_66), .B (n_63), .CI (n_77), .CO (n_86), .S
       (n_84));
  AND2_X1 g5859__5703(.A1 (n_113), .A2 (n_82), .ZN (n_83));
  FA_X1 g5861__7114(.A (A[1]), .B (B[1]), .CI (n_73), .CO (n_81), .S
       (n_82));
  DFFR_X1 \A_reg[3] (.RN (rstb), .CK (clk), .D (n_80), .Q (A[3]), .QN
       (UNCONNECTED11));
  DFFR_X1 \B_reg[0] (.RN (rstb), .CK (clk), .D (n_76), .Q (B[0]), .QN
       (UNCONNECTED12));
  AND2_X1 g5858__5266(.A1 (n_79), .A2 (n_78), .ZN (n_80));
  FA_X1 g5860__2250(.A (n_61), .B (n_21), .CI (n_64), .CO (n_77), .S
       (n_78));
  AND2_X1 g5866__6083(.A1 (n_113), .A2 (n_74), .ZN (n_76));
  MUX2_X1 g5868__2703(.A (n_67), .B (n_68), .S (W[3]), .Z (n_75));
  DFFR_X1 \A_reg[2] (.RN (rstb), .CK (clk), .D (n_69), .Q (A[2]), .QN
       (UNCONNECTED13));
  HA_X1 g5869__5795(.A (A[0]), .B (B[0]), .CO (n_73), .S (n_74));
  XNOR2_X1 g5862__7344(.A (n_71), .B (n_70), .ZN (n_72));
  NOR2_X1 g5867__1840(.A1 (n_91), .A2 (n_65), .ZN (n_69));
  NAND2_X1 g5872__5019(.A1 (n_67), .A2 (IN[3]), .ZN (n_68));
  DFFR_X1 \counter_reg[3] (.RN (rstb), .CK (clk), .D (n_62), .Q
       (counter[3]), .QN (UNCONNECTED14));
  FA_X1 g5865__1857(.A (n_23), .B (n_8), .CI (n_26), .CO (n_71), .S
       (n_66));
  FA_X1 g5878__9906(.A (n_6), .B (n_9), .CI (n_25), .CO (n_67), .S
       (n_70));
  XNOR2_X1 g5871__8780(.A (n_60), .B (n_59), .ZN (n_65));
  FA_X1 g5877__4296(.A (n_10), .B (n_3), .CI (n_24), .CO (n_63), .S
       (n_64));
  DFFR_X1 \OUT_reg[1] (.RN (rstb), .CK (clk), .D (n_49), .Q (OUT[1]),
       .QN (UNCONNECTED15));
  DFFR_X1 \counter_reg[2] (.RN (rstb), .CK (clk), .D (n_54), .Q
       (counter[2]), .QN (UNCONNECTED16));
  DFFR_X1 \OUT_reg[5] (.RN (rstb), .CK (clk), .D (n_47), .Q (OUT[5]),
       .QN (UNCONNECTED17));
  DFFR_X1 \OUT_reg[0] (.RN (rstb), .CK (clk), .D (n_51), .Q (OUT[0]),
       .QN (UNCONNECTED18));
  DFFR_X1 \OUT_reg[8] (.RN (rstb), .CK (clk), .D (n_50), .Q (OUT[8]),
       .QN (UNCONNECTED19));
  DFFR_X1 \OUT_reg[2] (.RN (rstb), .CK (clk), .D (n_44), .Q (OUT[2]),
       .QN (UNCONNECTED20));
  DFFR_X1 \OUT_reg[4] (.RN (rstb), .CK (clk), .D (n_45), .Q (OUT[4]),
       .QN (UNCONNECTED21));
  DFFR_X1 \OUT_reg[7] (.RN (rstb), .CK (clk), .D (n_57), .Q (OUT[7]),
       .QN (UNCONNECTED22));
  NOR2_X1 g5874__3772(.A1 (n_134), .A2 (n_55), .ZN (n_62));
  OR2_X1 g5875__1474(.A1 (n_58), .A2 (n_60), .ZN (n_61));
  DFFR_X1 \A_reg[1] (.RN (rstb), .CK (clk), .D (n_46), .Q (A[1]), .QN
       (UNCONNECTED23));
  DFFR_X1 \A_reg[0] (.RN (rstb), .CK (clk), .D (n_56), .Q (A[0]), .QN
       (UNCONNECTED24));
  DFFR_X1 \OUT_reg[9] (.RN (rstb), .CK (clk), .D (n_53), .Q (OUT[9]),
       .QN (UNCONNECTED25));
  DFFR_X1 \OUT_reg[3] (.RN (rstb), .CK (clk), .D (n_52), .Q (OUT[3]),
       .QN (UNCONNECTED26));
  DFFR_X1 \OUT_reg[6] (.RN (rstb), .CK (clk), .D (n_48), .Q (OUT[6]),
       .QN (UNCONNECTED27));
  DFFR_X1 \OUT_reg[10] (.RN (rstb), .CK (clk), .D (n_43), .Q (OUT[11]),
       .QN (UNCONNECTED28));
  DFFR_X1 \counter_reg[0] (.RN (rstb), .CK (clk), .D (n_42), .Q
       (counter[0]), .QN (UNCONNECTED29));
  HA_X1 g5876__4547(.A (n_22), .B (n_14), .CO (n_58), .S (n_59));
  INV_X1 g5895(.A (n_40), .ZN (n_57));
  NOR2_X1 g5900__9682(.A1 (n_91), .A2 (n_16), .ZN (n_56));
  NOR2_X1 g5879__2683(.A1 (n_28), .A2 (counter[3]), .ZN (n_55));
  AND2_X1 g5880__1309(.A1 (n_113), .A2 (n_29), .ZN (n_54));
  INV_X1 g5910(.A (n_32), .ZN (n_53));
  INV_X1 g5896(.A (n_38), .ZN (n_52));
  INV_X1 g5897(.A (n_37), .ZN (n_51));
  DFFR_X1 \counter_reg[1] (.RN (rstb), .CK (clk), .D (n_27), .Q
       (counter[1]), .QN (UNCONNECTED30));
  INV_X1 g5908(.A (n_34), .ZN (n_50));
  INV_X1 g5905(.A (n_41), .ZN (n_49));
  INV_X1 g5906(.A (n_30), .ZN (n_48));
  INV_X1 g5907(.A (n_35), .ZN (n_47));
  NOR3_X1 g5901__6877(.A1 (n_91), .A2 (n_60), .A3 (n_15), .ZN (n_46));
  INV_X1 g5909(.A (n_33), .ZN (n_45));
  INV_X1 g5911(.A (n_31), .ZN (n_44));
  INV_X1 g5912(.A (n_36), .ZN (n_43));
  NOR2_X1 g5926__2900(.A1 (n_134), .A2 (counter[0]), .ZN (n_42));
  AOI22_X1 g5913__2391(.A1 (n_39), .A2 (B[1]), .B1 (n_113), .B2
       (OUT[1]), .ZN (n_41));
  AOI22_X1 g5898__7675(.A1 (n_39), .A2 (B[7]), .B1 (n_113), .B2
       (OUT[7]), .ZN (n_40));
  AOI22_X1 g5899__7118(.A1 (n_39), .A2 (B[3]), .B1 (n_113), .B2
       (OUT[3]), .ZN (n_38));
  AOI22_X1 g5902__8757(.A1 (n_39), .A2 (B[0]), .B1 (n_113), .B2
       (OUT[0]), .ZN (n_37));
  INV_X1 g5927(.A (n_91), .ZN (n_79));
  AOI22_X1 g5920__1786(.A1 (n_39), .A2 (B[10]), .B1 (n_113), .B2
       (OUT[11]), .ZN (n_36));
  AOI22_X1 g5915__5953(.A1 (n_39), .A2 (B[5]), .B1 (n_113), .B2
       (OUT[5]), .ZN (n_35));
  AOI22_X1 g5916__5703(.A1 (n_39), .A2 (B[8]), .B1 (n_113), .B2
       (OUT[8]), .ZN (n_34));
  AOI22_X1 g5917__7114(.A1 (n_39), .A2 (B[4]), .B1 (n_113), .B2
       (OUT[4]), .ZN (n_33));
  AOI22_X1 g5918__5266(.A1 (n_39), .A2 (B[9]), .B1 (n_113), .B2
       (OUT[9]), .ZN (n_32));
  AOI22_X1 g5919__2250(.A1 (n_39), .A2 (B[2]), .B1 (n_113), .B2
       (OUT[2]), .ZN (n_31));
  AOI22_X1 g5914__6083(.A1 (n_39), .A2 (B[6]), .B1 (n_113), .B2
       (OUT[6]), .ZN (n_30));
  HA_X1 g5881__2703(.A (n_17), .B (counter[2]), .CO (n_28), .S (n_29));
  AND2_X1 g5928__5795(.A1 (n_113), .A2 (n_18), .ZN (n_27));
  NOR2_X1 g5929__7344(.A1 (n_39), .A2 (n_113), .ZN (n_91));
  INV_X1 g5930(.A (n_113), .ZN (n_134));
  INV_X1 g5921(.A (n_20), .ZN (n_26));
  INV_X1 g5922(.A (n_19), .ZN (n_25));
  HA_X1 g5923__1840(.A (n_1), .B (n_2), .CO (n_23), .S (n_24));
  HA_X1 g5924__5019(.A (n_7), .B (n_5), .CO (n_21), .S (n_22));
  HA_X1 g5925__1857(.A (n_0), .B (n_4), .CO (n_19), .S (n_20));
  OAI21_X2 g5932__9906(.A (counter[3]), .B1 (n_12), .B2 (counter[0]),
       .ZN (n_113));
  HA_X1 g5931__8780(.A (counter[0]), .B (counter[1]), .CO (n_17), .S
       (n_18));
  AND3_X1 g5933__4296(.A1 (n_11), .A2 (counter[0]), .A3 (counter[3]),
       .ZN (n_39));
  NOR2_X1 g5934__3772(.A1 (n_13), .A2 (n_16), .ZN (n_60));
  AOI22_X1 g5935__1474(.A1 (IN[1]), .A2 (W[0]), .B1 (IN[0]), .B2
       (W[1]), .ZN (n_15));
  INV_X1 g5936(.A (n_13), .ZN (n_14));
  INV_X1 g5944(.A (n_11), .ZN (n_12));
  AND2_X1 g5943__4547(.A1 (IN[1]), .A2 (W[2]), .ZN (n_10));
  NAND2_X1 g5942__9682(.A1 (IN[2]), .A2 (W[3]), .ZN (n_9));
  NAND2_X1 g5950__2683(.A1 (IN[1]), .A2 (W[3]), .ZN (n_8));
  AND2_X1 g5939__1309(.A1 (IN[2]), .A2 (W[0]), .ZN (n_7));
  NAND2_X1 g5951__6877(.A1 (IN[3]), .A2 (W[2]), .ZN (n_6));
  NAND2_X1 g5937__2900(.A1 (IN[0]), .A2 (W[0]), .ZN (n_16));
  NAND2_X1 g5938__2391(.A1 (IN[1]), .A2 (W[1]), .ZN (n_13));
  AND2_X1 g5940__7675(.A1 (IN[0]), .A2 (W[2]), .ZN (n_5));
  NAND2_X1 g5947__7118(.A1 (IN[2]), .A2 (W[2]), .ZN (n_4));
  NAND2_X1 g5949__8757(.A1 (IN[0]), .A2 (W[3]), .ZN (n_3));
  NAND2_X1 g5948__1786(.A1 (IN[3]), .A2 (W[0]), .ZN (n_2));
  AND2_X1 g5941__5953(.A1 (IN[2]), .A2 (W[1]), .ZN (n_1));
  AND2_X1 g5946__5703(.A1 (IN[3]), .A2 (W[1]), .ZN (n_0));
  NOR2_X1 g5945__7114(.A1 (counter[2]), .A2 (counter[1]), .ZN (n_11));
endmodule

